name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cd rocky
    - run: pwd
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kth-rocky:$(date +%s)
